name: sick_threes
description: A starter Flutter app for camera + ML tree labeling + map comments
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  image_picker: ^1.1.2
  google_mlkit_image_labeling: ^0.12.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  path_provider: ^2.1.4

  # UI helpers
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true